### ISSUE TITLE
Doesn’t work with Basecamp’s Trix editor

### ISSUE THREAD

**Issue by joeldrapper** [Zemke/instant-smart-quotes#1]
Thanks for building this extension. Text Substitutions are the one thing that kept me usigng Safari for most things. While using the extension, I noticed that Basecamp’s Trix editor isn’t supported.

You can see a demo of it here: https://trix-editor.org

**Comment by Zemke** [comment]
Yeah, it’s been the same for me with Safari. 

Thanks for the feedback. I’ll look into this issue and report back soon.

**Comment by joeldrapper** [comment]
Thank you! I’d be happy to submit a PR, but it’ll take me a while as I’ve got a pretty full schedule over the next few weeks.

**Comment by Zemke** [comment]
Wow! Trix is one awesome thing. I haven’t known of it—what a shame. 

It does a lot of things with the input field on its own already. The event that would trigger Instant Smart Quotes is not fired or not caught. That‘s why it’s not working, because it isn’t even called. It’s probably a countereffect of Trix interfering with manipulation of the input field. 

I don’t yet know why this is—I’ve noticed the same issue with iCloud and Apple’s office suite—but I see one great opportunity here. I’m thinking of proposing a feature to the Trix editor that would include built-in Instant Smart Quotes. I think that would be great addition for their editor. Also I’m currently working on supporting smart quotes for many different languages which Trix could also profit from.

**Comment by joeldrapper** [comment]
@Zemke that would be a great addition to Trix!

**Comment by Zemke** [comment]
This has been passed over the Trix project.

**Comment by Zemke** [comment]
They apparently won’t do it, but there’s #15 now.
