### ISSUE TITLE
Issues with the Markdown editor Dillinger

### ISSUE THREAD

**Issue by mistermantas** [Zemke/instant-smart-quotes#3]
Dillinger is a cloud-enabled, [open source](https://github.com/joemccann/dillinger) Markdown editor. The extension doesn’t work with it. The preview pane is fine but the doc itself doesn’t have smart quotes. You can check that by exporting the file.

[Screenshots](http://imgur.com/a/olkFp)

As far as I can understand, the extension only tries to replace dumb quotes in `<input>` or `<textarea>` fields, but Dillinger doesn’t use ‘em. So this issue should be reproducible on all browsers. [Take a look yourself](http://dillinger.io).

**Comment by mistermantas** [comment]
This probably isn't getting fixed and I want to clear my issues list, so I'll close this issue.

**Comment by mistermantas** [comment]
This probably isn't getting fixed and I want to clear my issues list, so I'll close this issue.

**Comment by Zemke** [comment]
Hey!

So, this is one of the pages where the editor—may it be an `input` or `textarea` or especially a `contenteditable` (supported since [v2.0.0](https://github.com/Zemke/instant-smart-quotes/releases/tag/2.0.0))—already does a lot of prcessing on the element itself and thereby interfering with Instant Smart Quotes.

There’s probably not a lot that can be done here, since the event handling of the page itself takes precedence over Instant Smart Quotes.

There’s some very awful examples of this. The worst I’ve seen is Apple’s web version of their notes app where even some Windows shortcuts like ctrl + some arrow key is prohibited.

**Comment by mistermantas** [comment]
Yup, I figured. At the time, I thought there was some fix, but alas…
